### ISSUE TITLE
inconsistent horizontal cursor movements at end of a headline

### ISSUE THREAD

**Issue by duianto** [Somelauw/evil-org-mode#12] opened 2017-07-21 12:02 UTC
### Description
The cursor moves in 3 different ways at the end of a headline, when it's contents are hidden, and there is an empty line above, below or on neither side of the contents.

### Scenario 1
No empty line above or below the contents.
```
* headline1
contents
```
The headlines contents are hidden:
`* headline1...`

With the cursor at the end of the line (on the first of the 3 dots), 
Moving forwards `l`, moves the cursor to the right of the 3 dots.

The following probably isn't a common behaviour, but if one tries to move forwards, then the cursor jumps back to the first of the 3 dots. 

In this state, trying to move forwards doesn't work, and trying to move backwards `h` requires 2 presses. And when the cursor moves, then it jumps 2 characters backwards. (info below) [1]

Setting `evil-move-beyond-eol` to `t` (default: `nil`), makes the cursor movements behave "normally", moving to the right stops at the end of the 3 dots, and moving to the left from the first of the 3 dots, works as expected.

### Scenario 2
Empty line above the contents:
```
* headline1

contents
```
The headlines contents are hidden:
`* headline1...`

Trying to move forwards from the end of the line (on the first of the 3 dots) doesn't work, but this might be expected behaviour, there probably is no reason to move the cursor past the 3 dots. (suggestion below) [2]

Moving to the left from the first of the 3 dots makes the cursor jump 2 characters to the left, over the `1`. (info below) [1]

Setting `evil-move-beyond-eol` to `t` (default: `nil`), doesn't stop the cursor on the first of the 3 dots. It jumps to the end of the 3 dots, and moving to the left works as expected.

### Scenario 3
Empty line below the contents and a second headline below the first:
```
* headline1
contents

* headline2
```
Headline1s contents are hidden:
```
* headline1...
* headline2
```

Moving forwards from the end of the line, moves the cursor to the right of the 3 dots. Trying to move forwards does nothing (expected behaviour), but trying to move backwards `h` doesn't work (unexpected behaviour).

Setting `evil-move-beyond-eol` to `t` (default: `nil`), and trying to move left `h`, still keeps the cursor stuck at the end of the 3 dots.

#### [1] Cursor jumps back 2 characters at end of the line
This happens in all scenarios.

With the cursor is at the end of the line (on the first of 3 dots), moving the cursor backwards `h` makes it jump over the `1` in `* headline1...`.

Setting `evil-move-beyond-eol` to `t` (default: `nil`), stops this behaviour.

#### [2] Should the cursor move past the 3 dots?
Maybe in all 3 scenarios, the cursor should stop moving forwards on the first of the 3 dots, since it's the end of the headline.

When the cursor is at the end of the 3 lines, then the mode line shows the cursors line and column position to be on the hidden contents. This can be dangerous. If one for example deletes some characters backwards `X`, then the characters are removed from the hidden contents. But any accidental changes won't be visible until the contents are shown again.

**Comment by Somelauw** [comment] 2017-07-24 15:40
Thanks for your report.

#### Scenario 1
I can reproduce moving past the end of the line and moving into the hidden text and moving back. This is potentially dangerous, because it doesn't "unfold" on typing or deleting commands. I can't reproduce [1]. It doesn't jump over the "1" for me.

#### Scenario 2:
I'm able to move passed the three final dots and back. This is also possible in scenario 1 and 3.

#### [1] Cursor jumps back 2 characters at end of the line.
This didn't happen to me. I was able to move on the 1 and back.

#### [2] Should the cursor move past the 3 dots?
I was able to move passed the 3 dots in all scenarios. This is indeed dangerous when using x on hidden context, but the same happens when you use backspace in pure Emacs. I really don't want to change the h and l commands unless absolutely necessary, but I'm open to other solutions that make evil-org safer.

**Comment by duianto** [comment] 2017-07-24 17:42
I forgot to include my system info.

#### System Info :computer:
- OS: windows-nt
- Emacs: 25.2.2
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. c2fe26dd)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion autohotkey colors emacs-lisp git helm markdown
                 (org :variables org-agenda-files
                      '("c:/Users/Username/Documents/"))
                 python version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES


Now I've also tested it without Spacemacs like this (the Spacemacs .emacs.d folder was still in the default directory):
start `emacs -Q` (-Q doesn't load any configurations)
`M-x` `package-initialize` `RET`
`M-:` `(require 'evil)` `RET`
`M-x` `evil-mode` `RET`
`C-x b` `test` `RET`
`M-x` `org-mode` `RET`
typed:
```
* headline1
contents
* headline2
```
and replicated the 3 scenarios.

I also tested them in Virtual box with Windows 10 as host and Ubuntu 16.10 as client, running Emacs 26.0.50, with both Spacemacs (develop) and Emacs (`-Q`, same steps as above).

All 3 scenarios happen like described in the initial post, including the cursor jumping over the `1` when moving left `h` from the first of the 3 dots, in both Windows and Ubuntu, with both Spacemacs and Emacs (`-Q`).

While testing in Emacs `-Q`, I hadn't enabled `evil-org-mode`, and discovered that it still was happening, so this issue isn't related to `evil-org-mode`.

**Comment by Somelauw** [comment] 2017-07-30 20:50
@duianto Using the instructions you gave, I'm able to replicate what you say and it indeed jumps over the "1"-digit.

You can stop this from happening by execution the following line:
```emacs-lisp
(setq evil-cross-lines t)
```

As you say, it's not really a problem with evil-org. I was able to get similar behaviour by using evil-mode in emacs-lisp on folded lines. So I'll close this issue.

**Closed by Somelauw** 2017-07-30 20:50 UTC
